id: P009558
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG3851
  title: ཁམས་སྤྲུལ་དོན་བརྒྱུད་ཉི་མའི་གསུང་ཁག་གཉིས
  author: ''
  volumes:
    70d520e1fc4f434d89bc6ed957670a6a:
      image_group_id: I1KG3938
      title: ''
      volume_number: 1
      total_pages: 24
      base_file: v001.txt
