id: IAEEA0445
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T02:39:00+00:00'
last_modified: '2022-06-08T11:52:58.098996+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3851
  title: ཁམས་སྤྲུལ་དོན་བརྒྱུད་ཉི་མའི་གསུང་ཁག་གཉིས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    110E:
      image_group_id: I1KG3938
      title: ''
      total_pages: 24
      order: 1
      base_file: 110E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
